### ISSUE TITLE
Error building engine

### ISSUE THREAD

**Issue by griz1112** [CnnDepth/tx2_fcnn_node#11]
Trying to see if this will run totally on the Xavier. Everything builds except the engine. I get this error. *** deserializing
Runtime created
engine created
fp16: 1
malloc_consolidate(): invalid chunk size
Aborted (core dumped)
Is this an arm vs intel issue?

**Comment by avbokovoy** [comment]
Some additional information needed:
1. Do you try to compile the default engine (the one in the "compile" section of the README.md)?
2. Did you try to compile it without --fp16 flag?
3. What options do you use in general to compile the engine?

I'm not sure if it's arm vs intel issue, since we didn't this kind of the problem both on x86_64 PC and Jetson TX2. We currently unable to test it with Xavier, but we will evaluate further as soon as our Xavier arrives (still being shipped).

**Comment by FPSychotic** [comment]
same error i jetson nANO jp 4.4.1, I needed aim to libcublas directory with -D flag. I followed the tutorial, tried change to ----int8 and next will try remove -fp16.

**Comment by MoscowskyAnton** [comment]
Hello! Faced this error on AGX Xavier, JetPack 4.3.
Used command from tutorial
```
rosrun tx2_fcnn_node fcrn_engine_builder --uff=./resnet_nonbt_shortcuts_320x240.uff --uffInput=tf/Placeholder \
  --output=tf/Reshape --height=240 --width=320 --engine=./test_engine.trt --fp16
```
Is solution still is unknown?
